In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import numpy as np

In [2]:
iris=load_iris()

In [3]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [4]:
#numpy array containing 0 to 2 values. Each one for a flower type. 0 for Setosa, 1 for Versicolor and 2 for Virginica
iris["target_names"],iris["target"]

(array(['setosa', 'versicolor', 'virginica'], 
       dtype='<U10'),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]))

In [5]:
#Description of each flower
iris["feature_names"] 

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
#shape of data
print(iris["data"].shape)

#measurement of of 10 flower
print(iris["data"][:10])

(150, 4)
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]]


In [7]:
#split the data for training and testing purpose
X_train,X_test,Y_train,Y_test=train_test_split(iris.data,iris.target,test_size=.25,random_state=33)

In [8]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(112, 4)
(38, 4)
(112,)
(38,)


In [9]:
from sklearn.preprocessing import StandardScaler 

In [10]:
#Make data standarized
scaler=StandardScaler().fit(X_train)

In [11]:
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [12]:
#predicting value flower
model=KNeighborsClassifier(n_neighbors=1)

In [13]:
model.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [14]:
predication=model.predict([[3,6,2,7]])
predication

array([2])

In [15]:
iris["target_names"][predication]

array(['virginica'], 
      dtype='<U10')

In [16]:
model.score(X_test,Y_test)

0.94736842105263153

In [17]:
#we can check accuracy depends of neighbours

In [18]:
from sklearn import metrics
for i in range(1,10):
    model=KNeighborsClassifier(n_neighbors=i)
    model.fit(X_train,Y_train)
    pred=model.predict(X_train)
    print("Accuracy of model at %d neighbors %f"%(i,metrics.accuracy_score(Y_train,pred)))#accuracy of model

Accuracy of model at 1 neighbors 1.000000
Accuracy of model at 2 neighbors 0.973214
Accuracy of model at 3 neighbors 0.982143
Accuracy of model at 4 neighbors 0.964286
Accuracy of model at 5 neighbors 0.973214
Accuracy of model at 6 neighbors 0.973214
Accuracy of model at 7 neighbors 0.973214
Accuracy of model at 8 neighbors 0.982143
Accuracy of model at 9 neighbors 0.973214
